test4/booktest/urls.py
from django.conf.urls import url
import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(\d+)/(\d+)$', views.show,name='show'),
    url(r'^index2$',views.index2,name='index2'),
    url(r'^user1',views.user1,name='user1'),
    url(r'^user2',views.user2,name='user2'),
    url(r'^htmlTest$', views.htmlTest),
    url(r'^csrf1$',views.csrf1),
    url(r'^csrf2$',views.csrf2),
    url(r'^verifycode$',views.verifycode),
    url(r'^verifytest1',views.verifytest1),
    url(r'^verifytest2',views.verifytest2),
]

test4/test4/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('booktest.urls',namespace='booktest'))
]

test4/booktest/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class BookInfo(models.Model):
    btitle=models.CharField(max_length=20)
    bpub_data=models.DateTimeField(db_column='pub_datae')
    bread=models.IntegerField()
    bcomment=models.IntegerField()
    isDelete=models.BooleanField()
    class Meta():
        db_table='bookinfo'

class HeroInfo(models.Model):
    hname=models.CharField(max_length=10)
    hgender=models.BooleanField()
    hcontent=models.CharField(max_length=1000)
    isDelete=models.BooleanField()
    book=models.ForeignKey('BookInfo')
    def showname(self):
        return self.hname

test4/booktest/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from models import *
# Create your views here.
from django.http import HttpResponse

def index(request):
    # hero=HeroInfo.objects.get(pk=1)
    # context={'hero':hero}
    list=HeroInfo.objects.filter(isDelete=False)
    context={'List':list}
    return render(request,'booktest/index_1.html',context)
def show(request, id,id2):
    context={'id':id}
    return render(request, 'booktest/show.html',context)

def index2(request):
    return render(request,'booktest/index2.html')
def user1(request):
    context={'uname':'xizong'}
    return render(request,'booktest/user1.html',context)
def user2(request):
    return render(request, 'booktest/user2.html')

def htmlTest(request):
    context={'t1':'<h1>123</h1>'}
    return render(request, 'booktest/htmlTest.html',context)

def csrf1(request):
    return render(request,'booktest/csrf1.html')
def csrf2(request):
    uname=request.POST['uname']
    return HttpResponse(uname)

def verifycode(request):
    from PIL import Image,ImageDraw,ImageFont
    import random
    bgcolor=(random.randrange(0,255),random.randrange(0,255),0)
    width=100
    height=25
    image=Image.new('RGB',(width,height),bgcolor)
    font=ImageFont.truetype('FreeMono.ttf',24)
    draw=ImageDraw.Draw(image)
    text='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz'
    texttemp=''
    for i in range(4):
        texttemp1=text[random.randrange(0,len(text))]
        texttemp+=texttemp1
        draw.text((i*25,0),
                  texttemp1,
                  (255,255,255),
                  font)
    request.session['code']=texttemp
    import cStringIO
    buf=cStringIO.StringIO()
    image.save(buf,'png')
    return HttpResponse(buf.getvalue(),'image/png')
def verifytest1(request):
    return render(request,'booktest/verifytest1.html')
def verifytest2(request):
    code1=request.POST['code1']
    code2=request.session['code']
    if code1==code2:
        return HttpResponse("ok")
    else:
        return HttpResponse("no")

test4/templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block head %}{% endblock %}
</head>
<body>
<h1>logo</h1>
<hr>
{% block content1 %}
<h1>abc</h1>
{% endblock %}
<hr>
<h1>contact {{ uname }}</h1>
</body>
</html>

test4/templates/booktest/base_goods.html
{% extends 'booktest/base.html' %}
{% block %}
{% endblock %}

test4/templates/booktest/base_user.html
{% extends 'booktest/base.html' %}
{% block content1 %}
<table border="1">
    <tr>
        <td height="300">user_navigation</td>
        <td>{% block user_content %}{% endblock %}</td>
    </tr>
</table>
{% endblock content1 %}

test4/templates/booktest/csrf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="csrf2" method="post">
    {% csrf_token %}
    <input type="text" name="uname">
    <input type="submit" value="confirm">
</form>
</body>
</html>

test4/templates/booktest/htmlTest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ t1 }}
<hr>
{{ t1|safe }}
<hr>
{% autoescape off %}
{{ t1 }}
{% endautoescape %}
{{ t2|default:'<h1>abc</h1>' }}
{{ t2|default:'&lt;h1&gt;abc&lt;h1&gt;' }}
</body>
</html>

test4/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'booktest:show' '456' '123' %}">link1</a>
{{ hero.hname }}
{{ hero.showname }}
<hr>
odd line show red color,even line show blue color
<hr>
<ur>
{% for hero in List  %}
    {% if forloop.counter|divisibleby:"2" %}
    <li style="color:red" >{{ forloop.counter }}:{{ hero.showname }}</li>
    {% else %}
    <li style="color:blue">{{ forloop.counter }}:{{ hero.showname }}</li>
    {% endif %}
    {% empty %}
    nothing for finding
{% endfor %}
</ur>
</body>
</html>

test4/templates/booktest/index2.html
{% extends 'booktest/base.html' %}
{% block content1 %}
<h1>123</h1>
{% endblock content1 %}

test4/templates/booktest/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ id }}
</body>
</html>

test4/templates/booktest/user1.html
{% extends 'booktest/base_user.html' %}
{% block head %}
<script>alert('123')</script>
{% endblock head %}

{% block user_content %}
<h1>user certer1</h1>
{% endblock user_content %}

test4/templates/booktest/user2.html
{% extends 'booktest/base_user.html' %}
{% block user_content %}
<h1>user certer2</h1>
{% endblock user_content %}

test4/templates/booktest/verifytest1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="verifytest2" method="post">
    {% csrf_token%}
    <input type="text" name="code1">
    <img src="verifycode">
    <input type="submit" value="conform">
</form>
</body>
</html>